name: CI

on:
  pull_request:
    branches: [master]
  merge_group:
    branches: [master]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  FORCE_COLOR: 3

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./setup

      - name: Check
        run: pnpm check

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./setup

      - name: Typecheck
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm typecheck
